services:
  nextjs:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    container_name: medication-db-nextjs

    working_dir: /workspace

    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules

    ports:
      - "3000:3000"
      - "8080:8080"

    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}

    command: sleep infinity

    networks:
      - mdi-network

    stdin_open: true
    tty: true
networks:
  mdi-network:
    external: true

volumes:
  node_modules:
